DROP TABLE PACIENTE;
DROP TABLE ESPECIALIDADE;
DROP TABLE MEDICOS;
DROP TABLE CONSULTA;

CREATE TABLE PACIENTE (
    ID_PAC NUMBER(10) PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(120) NOT NULL,
    DATA_NASC DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    CPF VARCHAR2(14) UNIQUE,
    CONSTRAINT CK_GENERO_PAC CHECK(GENERO IN ('M', 'F'))
); 

CREATE TABLE ESPECIALIDADE (
    ID_ESP NUMBER(10) PRIMARY KEY, 
    NOME VARCHAR2(120) UNIQUE NOT NULL
);

CREATE TABLE MEDICO (
    CRM NUMBER(10) PRIMARY KEY,
    NOME_MEDICO VARCHAR2(120) NOT NULL,
    DATA_NASC DATE NOT NULL, 
    GENERO CHAR(1) NOT NULL, 
    ID_ESP NUMBER(10) NOT NULL,  
    CONSTRAINT CK_GENERO_MED CHECK(GENERO IN ('M', 'F')),
    CONSTRAINT FK_ESP_MED FOREIGN KEY (ID_ESP) REFERENCES ESPECIALIDADE(ID_ESP)
);

CREATE TABLE CONSULTA (
    CRM NUMBER(10) NOT NULL, 
    ID_PAC NUMBER(10) NOT NULL,
    DTH_AGENDAMENTO DATE NOT NULL, 
    TIPO CHAR(1) NOT NULL, 
    STATUS CHAR(1) NOT NULL, 
    OBSERVACAO VARCHAR2(512),

    CONSTRAINT CK_TIPO_CONSUL CHECK (TIPO IN ('C', 'R')),
    CONSTRAINT CK_STATUS_CONSUL CHECK (STATUS IN ('A', 'C', 'R')),
    CONSTRAINT FK_CRM_CONSUL FOREIGN KEY (CRM) REFERENCES MEDICO(CRM),
    CONSTRAINT FK_ID_PAC FOREIGN KEY (ID_PAC) REFERENCES PACIENTE(ID_PAC),
    CONSTRAINT PK_CONSULTA PRIMARY KEY (CRM, ID_PAC, DTH_AGENDAMENTO)
);
