CREATE DATABASE PRODUTO;

CREATE TABLE TIPO_PRODUTO(
    ID_TP NUMBER(2) PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    CONSTRAINT UQ_TP_NOME UNIQUE(NOME)
);

CREATE TABLE PRODUTO(
    ID NUMBER(3),
    NOME VARCHAR2(120) NOT NULL,
    PRECO_COMPRA NUMBER(8,2),
    PRECO_VENDA NUMBER(9,2) NOT NULL,
    DESCRICAO VARCHAR2(4000) NULL,
    ESTOQUE NUMBER(5) NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
    ID_TP NUMBER(2),
    DTH_ULTIMA_COMPRA DATE,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID),
    CONSTRAINT UQ_PRODUTO_NOME UNIQUE (NOME),
    CONSTRAINT FK_PRODUTO_TIPO FOREIGN KEY (ID_TP) REFERENCES TIPO_PRODUTO(ID_TP),
    CONSTRAINT CK_PRODUTO_ATIVO CHECK (ATIVO IN ('S', 'N'))
);

INSERT INTO PRODUTO(ID, NOME, PRECO_COMPRA, PRECO_VENDA, DESCRICAO, ESTOQUE, ATIVO, ID_TP, DTH_ULTIMA_COMPRA)
VALUES (10, 'CANETA BIC', 1.32, 2, NULL, 120, 'S', NULL, TO_DATE('20/09/2025','DD/MM/YYYY'));

CREATE SEQUENCE SEQ_TP 
START WITH 1
INCREMENT BY 1
MAXVALUE 99
NOCYCLE
NOCACHE;

INSERT INTO TIPO_PRODUTO(ID_TP, NOME)
    VALUES (SEQ_TP.NEXTVAL, 'MATERIAL LIMPEZA');

INSERT INTO TIPO_PRODUTO(ID_TP, NOME)
    VALUES (SEQ_TP.NEXTVAL, 'MATERIAL ESCRITORIO');

INSERT INTO TIPO_PRODUTO(ID_TP, NOME)
    VALUES (SEQ_TP.NEXTVAL, 'MATERIAL CONSTRUÇÃO');     

INSERT INTO PRODUTO(ID, NOME, PRECO_COMPRA, PRECO_VENDA, DESCRICAO, ESTOQUE, ATIVO, ID_TP, DTH_ULTIMA_COMPRA)
    VALUES (22, 'MARTELO', 13.33, 26.50, 'MARTELO REDONDO', 10, 'S', 3, TO_DATE('21/09/2025 17:05:08', 'DD/MM/YYYY HH24:MI:SS'));

UPDATE PRODUTO
SET PRECO_COMPRA = 14.80,
    ESTOQUE = ESTOQUE + 10,
    DTH_ULTIMA_COMPRA = TO_DATE('29/09/2025', 'DD/MM/YYYY')
WHERE ID = 22;

UPDATE PRODUTO
SET ID_TP = 2
WHERE ID = 10;

UPDATE PRODUTO
SET PRECO_COMPRA = PRECO_COMPRA + (PRECO_COMPRA * 0.05);

INSERT INTO TIPO_PRODUTO(ID_TP, NOME)
    VALUES (12, 'ESCRITORIO');

UPDATE PRODUTO
SET ID_TP = 12
WHERE ID_TP = 2;

DELETE FROM PRODUTO;
DELETE FROM TIPO_PRODUTO;

DROP TABLE PRODUTO;
DROP TABLE TIPO_PRODUTO;
    
COMMIT;